project:
  type: website

website:
  title: "ISSS608-Y25-26-Group2"
  navbar:
    pinned: True
    right:
      - href: index.qmd
        text: Home
      - text: Overview
      - text: Shiny App
        menu:
        - text: "Shiny App"
          href: https://huahsuan2000.shinyapps.io/Shinyapp-group/
        - text: "User Guide"
          href: "Shinyapp/user_guide.html"
      - text: Prototype
        menu: 
        - text: "EDA and CDA"
          href: "Prototype/EDA_CDA.html"
        - text: "Cluster Analysis"
          href: "Prototype/Cluster.html"
        - text: "Predict Model"
          href: "Prototype/Predict_Model.html"
      - text: Team
        menu:
        - text: "Project Proposal"
          href: "Team/Proposal.html"
        - text: "Minutes of Meeting"
          href: "Team/minutes_of_meeting.html"

format:
  html:
    theme: flatly
    toc: true

editor: visual
